### ISSUE TITLE
Silence the output from `vapor heroku init`

### ISSUE THREAD

**Issue by oarrabi** [qutheory/vapor-toolbox#22]
Since we moved from `git remote get-url origin` to `git remote show origin` the output became more chatty.

The old output was `https://git.heroku.com/vapor-test-swift.git` 
The new output
```
* remote heroku
  Fetch URL: https://git.heroku.com/vapor-test-swift.git
  Push  URL: https://git.heroku.com/vapor-test-swift.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

We can solve this by discarding the output from STDOUT a file and check the status code of executing the command.

Note: 
When executing `git remote show origin` the return code is 0 if heroku exists and 128 if it does not.

PR related:
https://github.com/qutheory/vapor-cli/pull/21

**Comment by tannernelson** [comment]
This is was added in 0.6
