### ISSUE TITLE
Add support for Vapor’s commands

### ISSUE THREAD

**Issue by feinstruktur** [qutheory/vapor-toolbox#33]
From https://github.com/qutheory/vapor-cli/pull/30#issuecomment-227520276 :

The Vapor commands can be read about in the docs here: https://vapor.readme.io/v0.12/docs/command

Basically Vapor has a little bit of CLI functionality itself now for serving and running preparations (migrations).

You run this by doing `.build/debug/App serve` `.build/debug/App prepare --revert` etc.

I want to make the CLI reduce the typing here by doing `vapor run serve`

To accomplish this we would need to parse the Package.swift to figure out the name of the package, then  run the executable from either the debug or release folders.

so something like `vapor run serve --release` would translate to `.build/release/MyAppName serve`

**Comment by tannernelson** [comment]
This has been added in 0.6
