### ISSUE TITLE
Consolidate console functionality between `vapor-cli` and `vapor`

### ISSUE THREAD

**Issue by feinstruktur** [qutheory/vapor-toolbox#34]
From https://github.com/qutheory/vapor-cli/pull/30#issuecomment-227520630 :

Also if you look at the console stuff powering that, you can see there's some cool code here for doing colors, etc.

I think it could be worth breaking this out into it's own package so both Vapor and the CLI can use it: https://github.com/qutheory/vapor/tree/master/Sources/Vapor/Console

**Comment by tannernelson** [comment]
https://github.com/qutheory/console

**Comment by tannernelson** [comment]
Most functionality has been moved from the CLI into `qutheory/console` and will be used in Vapor 0.14.
