### ISSUE TITLE
Change update URL for spm based install/update

### ISSUE THREAD

**Issue by feinstruktur** [qutheory/vapor-toolbox#35]
With changing to SPM based building came a change to how the script is installed. Instead of downloading the actual script and compiling it in place, with SPM based install we pull down a `bootstrap.swift` script that builds and installs the `vapor` binary.

That also means these two mechanisms need different files to be served from the install URL. It is probably not a good idea to change `cli.qutheory.io` to serving `bootstrap.swift`, because it will break the update mechanism of all older versions of `vapor-cli`. Instead, it would be better to add a new endpoint, for example

http://vapor-cli.qutheory.io

which would serve `bootstrap.swift` and in tandem we will then change the SPM installers update URL to this.

I went ahead and have done this in anticipation of us making this change here: 6ce5ba17301201703e0c7ae9274c1d0e760172f8

**Comment by tannernelson** [comment]
I've added `toolbox.qutheory.io`
