### ISSUE TITLE
Add check for Ubuntu

### ISSUE THREAD

**Issue by thomasphorton** [qutheory/vapor-toolbox#46]
When installing on Ubuntu without swiftenv, the bootstrap script looks for the string `swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a` (`SWIFT_VERSION`) in the path. An earlier step in the documentation has the user rename the folder to `swift`, causing this check to fail and the script to exit.

https://github.com/qutheory/vapor-toolbox/blob/master/bootstrap.sh#L24

Quick fix was to skip the rename step, but there is probably a better way so the documentation can remain consistent across platforms.

**Comment by tannernelson** [comment]
I think this will be solved when the toolbox switches to Swift 3.0 preview 2.
