### ISSUE TITLE
Xcode 8 beta 3

### ISSUE THREAD

**Issue by procek69** [qutheory/vapor-toolbox#51]
Checking at check.qutheory.io doesn't work with new beta of xcode.

**Comment by procek69** [comment]
![zrzut ekranu 2016-07-26 o 19 33 55](https://cloud.githubusercontent.com/assets/16499887/17148563/f9c899ec-5367-11e6-8d9c-4e22506cc7ea.png)

**Comment by tannernelson** [comment]
The next version of Vapor and the toolbox will support the latest Xcode.

**Comment by joernroeder** [comment]
do you have any plans when you will publish a beta 3 compatible release? I've updated already to beta 3 and a the old snapshot seems incompatible with it and the older beta 2 isn't listed in apples developer download section anymore.

**Comment by tannernelson** [comment]
Hopefully this week!

**Comment by joernroeder** [comment]
🆒👍

**Comment by urmyfaith** [comment]
Hopefully this week too!

**Comment by urmyfaith** [comment]
now works for Xcode 8 beta 3?

![pic1](http://ww1.sinaimg.cn/large/006tNc79gw1f6cf39ijjij30e004h3z7.jpg)

![pic2](http://ww4.sinaimg.cn/large/006tNc79gw1f6cf3968ahj30l607yju9.jpg)

**Comment by tannernelson** [comment]
Yup! Looks like you just need to do `swiftenv install DEVELOPMENT-SNAPSHOT-2016-07-25-a`

**Comment by urmyfaith** [comment]
I will have a try. thanks.

**Comment by joernroeder** [comment]
Thanks! Works like a charm!
