### ISSUE TITLE
Unable to install Vapor Toolbox

### ISSUE THREAD

**Issue by JesseTellez** [qutheory/vapor-toolbox#52]
when running the command:

curl -sL toolbox.qutheory.io | bash

It gets stuck after Compiling once "Installing..." shows up.
Im sure I have the correct swift version and xcodebuild, but this step just stalls.

When I check vapor --help I receive:

/usr/local/bin/vapor:40:18: error: missing argument label 'message:' in call
            fail("Invalid number of arguments.")
                 ^
                 message: 
/usr/local/bin/vapor:60:18: error: missing argument label 'message:' in call
            fail("Unknown command: \(Process.arguments[1])")
                 ^
                 message: 
/usr/local/bin/vapor:95:22: error: 'system' is unavailable in Swift: Use posix_spawn APIs or NSTask instead.
        let result = system(command)
                     ^~~~~~
Darwin.system:3:13: note: 'system' has been explicitly marked unavailable here
public func system(_: UnsafePointer<Int8>!) -> Int32
            ^
/usr/local/bin/vapor:104:21: error: missing argument label 'command:' in call
            try run(command)
                    ^
                    command: 
/usr/local/bin/vapor:106:18: error: missing argument label 'message:' in call
            fail(errorMessage)
                 ^
                 message: 
/usr/local/bin/vapor:116:12: error: missing argument label 'command:' in call
        run("rm -rf Packages .build", orFail: "Could not clean")
           ^
            command: 
/usr/local/bin/vapor:134:21: error: missing argument label 'command:' in call
            try run("swift build \(buildFlags)")
                    ^
                    command: 
/usr/local/bin/vapor:143:18: error: missing argument label 'message:' in call
            fail("Could not build project.")
                 ^
                 message: 
/usr/local/bin/vapor:149:12: error: missing argument label 'command:' in call
        run("mkdir -p .build", orFail: "Could not create .build directory")
           ^
            command: 
/usr/local/bin/vapor:178:21: error: missing argument label 'command:' in call
            try run("\(cc) \(cflags) \(files) -I \(include) -L \(lib) -lVapor -lJay -lHummingbird -llibc -lStrand \(rpath) -o .build/VaporApp")
                    ^
                    command: 
/usr/local/bin/vapor:186:18: error: missing argument label 'message:' in call
            fail("Could not build project.")
                 ^
                 message: 
/usr/local/bin/vapor:196:25: error: missing argument label 'command:' in call
                try run(".build/VaporApp")
                        ^
                        command: 
/usr/local/bin/vapor:211:25: error: missing argument label 'command:' in call
                try run(".build/\(folder)/\(name) \(args)")
                        ^
                        command: 
/usr/local/bin/vapor:215:22: error: missing argument label 'message:' in call
                fail("Could not run project")
                     ^
                     message: 
/usr/local/bin/vapor:218:18: error: missing argument label 'message:' in call
            fail("Unknown error")
                 ^
                 message: 
/usr/local/bin/vapor:225:18: error: missing argument label 'message:' in call
            fail("Invalid number of arguments.")
                 ^
                 message: 
/usr/local/bin/vapor:231:21: error: missing argument label 'command:' in call
            try run("mkdir \(escapedName)")
                    ^
                    command: 
/usr/local/bin/vapor:232:21: error: missing argument label 'command:' in call
            try run("curl -L https://github.com/qutheory/vapor-example/archive/master.tar.gz > \(escapedName)/vapor-example.tar.gz")
                    ^
                    command: 
/usr/local/bin/vapor:233:21: error: missing argument label 'command:' in call
            try run("tar -xzf \(escapedName)/vapor-example.tar.gz --strip-components=1 --directory \(escapedName)")
                    ^
                    command: 
/usr/local/bin/vapor:234:30: error: missing argument label 'command:' in call
            let _ = try? run("rm \(escapedName)/vapor-example.tar.gz")
                             ^
                             command: 
/usr/local/bin/vapor:240:18: error: missing argument label 'message:' in call
            fail("Could not clone repository")
                 ^
                 message:

**Comment by tannernelson** [comment]
It seems like you still have the old CLI installed. Try deleting it and running the new install script again.
