### ISSUE TITLE
Dockerfile has incorrect SWIFT_BRANCH

### ISSUE THREAD

**Issue by UberJason** [qutheory/vapor-toolbox#57]
Hi there,

I got Vapor running locally and was trying to get it running in Docker. When I used `vapor docker init` and then `vapor docker build`, I got a build error:

`Error: Docker build failed: The command '/bin/sh -c SWIFT_ARCHIVE_NAME=swift-$SWIFT_VERSION-$SWIFT_PLATFORM &&     SWIFT_URL=https://swift.org/builds/$SWIFT_BRANCH/$(echo "$SWIFT_PLATFORM" | tr -d .)/swift-$SWIFT_VERSION/$SWIFT_ARCHIVE_NAME.tar.gz &&     wget -q $SWIFT_URL &&     wget -q $SWIFT_URL.sig &&     gpg --verify $SWIFT_ARCHIVE_NAME.tar.gz.sig &&     tar -xzf $SWIFT_ARCHIVE_NAME.tar.gz --directory / --strip-components=1 &&     rm -rf $SWIFT_ARCHIVE_NAME* /tmp/* /var/tmp/*' returned a non-zero code: 8`

I dug deep for a while and discovered that in my version of Swift (which is **DEVELOPMENT-SNAPSHOT-2016-07-25-a**), the URL for fetching the Swift snapshot is being constructed incorrectly because `SWIFT_BRANCH` is set to **swift-3.0-preview-2**. Note that I used **DEVELOPMENT-SNAPSHOT-2016-07-25-a** in accordance with your [YouTube video](https://www.youtube.com/watch?v=YxvQo-EH2AA) from a few days ago. 

When, however, I change `SWIFT_BRANCH` to **development**, to correctly construct the URL, then Docker is able to build the image.

I don't really have a fix for this because I'm a Docker noob, but I wanted to mention it to you. Perhaps you can have some logic to match the SWIFT_BRANCH with the SWIFT_VERSION better, or allow it to be passed in as a docker build argument?

**Comment by tannernelson** [comment]
Thanks for catching this! I pushed an updated Dockerfile. Let me know if it works.

**Comment by UberJason** [comment]
Thanks! So do you just periodically update the file manually to keep up with the Swift snapshots?

**Comment by tannernelson** [comment]
It's in the master branch of this repo, so it _should_ get updated whenever we update the toolbox. But I think I forgot.
