### ISSUE TITLE
clean build

### ISSUE THREAD

**Issue by tannernelson** [qutheory/vapor-toolbox#8]
It would be nice to have a flag `--clean` on `vapor build` that would perform `vapor clean` first.

**Comment by feinstruktur** [comment]
How about command chaining like `make` has? As in `vapor clean build` or maybe even `vapor clean build run`.

Might be tricky with commands like `build` that are valid in different contexts though. Could see that working only for top level commands.

**Comment by tannernelson** [comment]
We tried command chaining in an early version of the CLI and it made more headache than good unfortunately. 

Our goal is to have commands past `vapor run ...` go to the Vapor console (eg: `vapor run migrate`). Things like this could interfere with the chaining.

**Comment by tannernelson** [comment]
This has been added in 0.6
